chore: add screenshare audio video enabled methods
livekit/client-sdk-flutter pull request #473
Opened 2024-02-26 12:50 UTC by td-famedly

2024-02-26 12:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/livekit/client-sdk-flutter?pullRequest=473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/livekit/client-sdk-flutter?pullRequest=473) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/livekit/client-sdk-flutter?pullRequest=473) it.</sub>

2024-02-29 01:08 UTC, cloudwebrtc requested changes

2024-02-29 09:53 UTC, td-famedly commented on lib/src/participant/participant.dart
> +  bool isScreenShareVideoEnabled() {
fixed

2024-02-29 09:53 UTC, td-famedly commented on lib/src/participant/participant.dart
> +  /// Convenience property to check whether [TrackSource.screenShareVideo] is published or not.
fixed

2024-02-29 10:32 UTC, cloudwebrtc approved these changes
lg!

2024-02-29 10:33 UTC, merged